### PR TITLE
Services branch 

### LINKED ISSUE #45: Some phones do not display two icons on a row
28881602491011_ pic

eg: iphone 11
      oppo A11    PCHM10

### LINKED ISSUE #65: Credentials：After the edited information is saved, the current interface is not automatically refreshed

### LINKED ISSUE #74: When there is no operation that needs to be done by the user under "Current Actions", give relevant text description, do not directly blank
29451603771268_ pic

### LINKED ISSUE #75: The icon that the certificate has been published on the chain is not displayed completely on some phones
29461603771841_ pic_hd
OPPAO A11， PCHM10

### LINKED ISSUE #78: Frame of avatar: inconsistent size
29491603774205_ pic
29501603774206_ pic

### LINKED ISSUE #88: In light mode: On the Profile page, the "Country" icon is not displayed
30161604545452_ pic_hd

### PR DESCRIPTION
**Pull request by dchagastelles**
- edit-profile page with switch to show on public profile
- Resign Home, Profile, Credentails-Details and Credentials Page to follow new design
- Refactoring profileService, remove a lot of duplicated code and commented code. 

- Implemented #27
- Implemented #86
- Implemented #82

- Fix #88
- Fix #78
- Fix #75 (the icon in not used anymore)
- Fix #74
- Fix #65
- Fix #45 (no more actionsheet menu)

### CODE REVIEW

**Comment by kpachhai** [comment]
On credentials page, the published icon is not highlighted for any of the credentials even if my creds have been published. The verified icon works nicely though.

**Comment by kpachhai** [comment]
Feedback 2: Also, previously, we were showing "Verified by XXXX" directly on credentials page but now we don't as part of this new design. Any reason?

**Comment by kpachhai** [comment]
Feedback 3: On a verified credential detail page, nothing shows up(previously, it would show me two tabs - one that showed the validator and the other one being history tab). Now, credential detail page is just blank

**Comment by kpachhai** [comment]
Feedback 4: My avatar credential is under "Hidden" tab on credentials page. Avatar should always be visible no matter what

**Comment by kpachhai** [comment]
Feedback 5: On application credential detail page, there's an Edit button and clicking this button takes users to the main Edit page that lets you edit basic profile details. We should just disable the Edit button on all the credential details page and only have this button for basic profile credentials. Or better yet, just remove the Edit button from all the credential detail pages as it's not needed. We already have edit button on home page.

**Comment by kpachhai** [comment]
Feedback 6: Can we make the text size a bit smaller on the main credentials page. My short email address is overflowing to the next line even on my big screened mobile device. I see that there's more extra space on the left side of the page. Maybe we can make these boxes wider so they also occupy more space width wise?

**Comment by kpachhai** [comment]
Feedback 7: I don't see a "Verify now" button for credentials that haven't been verified yet. Since we have disabled this button, we don't need to worry about it but I think we should still implement this and then comment it out. We will be re-enabling this button in the near future so need to be ready for that.

**Comment by dchagastelles** [comment]
Created a new PR because the correction were made in new branch

**Pull request closed without merging**
